#!/bin/zsh
set -x


RUN_BUNDLE_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)/../.."
RUN_ROM_PATH="${RUN_BUNDLE_DIR}/Contents/Resources/Roms/Halo2600.a26"

RUN_EMU_PATH="/Applications/Stella.app"


if ! [ -e "$RUN_EMU_PATH" ]; then
  echo "Error: Stella not found at $RUN_EMU_PATH." >&2
  echo "Download from https://stella-emu.github.io" >&2
  exit 1
fi



# Run the emulator with the default config
open "${RUN_EMU_PATH}" --args -fullscreen 1 "${RUN_ROM_PATH}"


