#!/bin/zsh

# platypus copies this file into Resources and names it 'script'

echo 'Welcome to RetroApp' >&2
echo "Received $# argument(s):" >&2
for arg in "$@"; do echo "  $arg"; done

RESOURCES_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)

/bin/zsh -l "$RESOURCES_DIR/cli/retroapp" droplet "$@"

if [ "$?" -eq 0 ]; then
  echo "\n\nSUCCESS" >&2
else
  echo "\n\nFAILURE" >&2
fi

exit 0