#!/bin/zsh

# platypus copies this file into Resources and names it 'script'

print "Running RetroAppMaker"
print "Received $# argument(s):"
for arg in "$@"; do echo "  $arg"; done

RESOURCES_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)

/bin/zsh -l "$RESOURCES_DIR/cli/retroapp" drag "$@"
exit_code=$?
